AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Stack for etude-fastapi-dev

Globals:
  Function:
    Timeout: 5

Resources:
  EtudeFastapiFunc:
    Type: AWS::Serverless::Function
    Properties:
      Description: ""
      CodeUri: src/
      FunctionName: etude-fastapi-dev
      Handler: run.handler
      Runtime: python3.9
      Environment:
        Variables:
          SETTINGS: "develop"
      Timeout: 600
      MemorySize: 512
      Role: arn:aws:iam::768515502995:role/role-lambda-upload
      Architectures:
        - x86_64
      Events:
        EtudeFastapi:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  EtudeFastapiApi:
    Description: "An Api gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  EtudeFastapiFunc:
    Description: "ARN for etude-fastapi-dev"
    Value: !GetAtt EtudeFastapiFunc.Arn
  EtudeFastapiIamRole:
    Description: "Explicit IAM Role on develop "
    Value: arn:aws:iam::768515502995:role/role-lambda-upload
